services:

  zuhoor:
    build: .
    container_name: zuhoor-app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: zuhoor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: gazi706948
      MYSQL_DATABASE: zuhoor_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
